
No sentence-transformers model found with name /home/athekunal/.cache/torch/sentence_transformers/ProsusAI_finbert. Creating a new one with MEAN pooling.
Some weights of the model checkpoint at /home/athekunal/.cache/torch/sentence_transformers/ProsusAI_finbert were not used when initializing BertModel: ['classifier.bias', 'classifier.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2023-07-21 21:12:13.205 Uncaught app exception
Traceback (most recent call last):
  File "/home/athekunal/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/athekunal/SEC-Project/SEC-QA-Agent/streamlit.py", line 2, in <module>
    from main import SEC_LLM
  File "/home/athekunal/SEC-Project/SEC-QA-Agent/main.py", line 9, in <module>
    restore_collection = load_vector_store_local("./sec-10-K","10-K",if_finbert=True)
  File "/home/athekunal/SEC-Project/SEC-QA-Agent/load_database.py", line 53, in load_vector_store_local
    chroma_restore_client = chromadb.Client(
  File "/home/athekunal/.local/lib/python3.10/site-packages/chromadb/__init__.py", line 31, in Client
    api = system.instance(API)
  File "/home/athekunal/.local/lib/python3.10/site-packages/chromadb/config.py", line 162, in instance
    impl = type(self)
  File "/home/athekunal/.local/lib/python3.10/site-packages/chromadb/api/local.py", line 64, in __init__
    self._db = self.require(DB)
  File "/home/athekunal/.local/lib/python3.10/site-packages/chromadb/config.py", line 114, in require
    inst = self._system.instance(type)
  File "/home/athekunal/.local/lib/python3.10/site-packages/chromadb/config.py", line 162, in instance
    impl = type(self)
  File "/home/athekunal/.local/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 445, in __init__
    self.load()
  File "/home/athekunal/.local/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 503, in load
    self._conn.execute(
duckdb.InvalidInputException: Invalid Input Error: No magic bytes found at end of file './sec-10-K/chroma-embeddings.parquet'
[34m  Stopping...