
No sentence-transformers model found with name /home/athekunal/.cache/torch/sentence_transformers/ProsusAI_finbert. Creating a new one with MEAN pooling.
Some weights of the model checkpoint at /home/athekunal/.cache/torch/sentence_transformers/ProsusAI_finbert were not used when initializing BertModel: ['classifier.bias', 'classifier.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2023-07-20 23:13:52.724 Uncaught app exception
Traceback (most recent call last):
  File "/home/athekunal/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/athekunal/SEC-Project/SEC-QA-Agent/streamlit.py", line 13, in <module>
    generate_response(text)
  File "/home/athekunal/SEC-Project/SEC-QA-Agent/streamlit.py", line 7, in generate_response
    st.info(SEC_LLM(input_text))
  File "/home/athekunal/SEC-Project/SEC-QA-Agent/main.py", line 12, in SEC_LLM
    llm1_output_dict, query_metadata = get_response_llm1(USER_REQUEST,"10-K")
  File "/home/athekunal/SEC-Project/SEC-QA-Agent/LLM1.py", line 91, in get_response_llm1
    query_metadata = get_query_metadata(llm1_output_dict)
TypeError: get_query_metadata() missing 1 required positional argument: 'doc_name'
[34m  Stopping...