No sentence-transformers model found with name /home/athekunal/.cache/torch/sentence_transformers/ProsusAI_finbert. Creating a new one with MEAN pooling.
Some weights of the model checkpoint at /home/athekunal/.cache/torch/sentence_transformers/ProsusAI_finbert were not used when initializing BertModel: ['classifier.weight', 'classifier.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "/home/athekunal/SEC-Project/wandb_MLOPs/main.py", line 13, in <module>
    relevant_sentences = get_relevant_docs(llm1_output_dict,query_metadata,restore_collection)
  File "/home/athekunal/SEC-Project/wandb_MLOPs/load_database.py", line 63, in get_relevant_docs
    query_results = restore_collection.query(
  File "/home/athekunal/.local/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 213, in query
    query_embeddings = self._embedding_function(
TypeError: 'HuggingFaceEmbeddings' object is not callable
Traceback (most recent call last):
  File "/home/athekunal/SEC-Project/wandb_MLOPs/main.py", line 13, in <module>
    relevant_sentences = get_relevant_docs(llm1_output_dict,query_metadata,restore_collection)
  File "/home/athekunal/SEC-Project/wandb_MLOPs/load_database.py", line 63, in get_relevant_docs
    query_results = restore_collection.query(
  File "/home/athekunal/.local/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 213, in query
    query_embeddings = self._embedding_function(
TypeError: 'HuggingFaceEmbeddings' object is not callable