No sentence-transformers model found with name /home/athekunal/.cache/torch/sentence_transformers/ProsusAI_finbert. Creating a new one with MEAN pooling.
Some weights of the model checkpoint at /home/athekunal/.cache/torch/sentence_transformers/ProsusAI_finbert were not used when initializing BertModel: ['classifier.bias', 'classifier.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2023-07-21 21:14:11.425 Uncaught app exception
Traceback (most recent call last):
  File "/home/athekunal/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/athekunal/SEC-Project/SEC-QA-Agent/streamlit.py", line 2, in <module>
    from main import SEC_LLM
  File "/home/athekunal/SEC-Project/SEC-QA-Agent/main.py", line 9, in <module>
    restore_collection = load_vector_store_local("./sec-10-K-finbert","10-K",if_finbert=True)
  File "/home/athekunal/SEC-Project/SEC-QA-Agent/load_database.py", line 60, in load_vector_store_local
    restore_collection = chroma_restore_client.get_collection(name=collection_name,embedding_function=embedding_fn)
  File "/home/athekunal/.local/lib/python3.10/site-packages/chromadb/api/local.py", line 180, in get_collection
    raise ValueError(f"Collection {name} does not exist")
ValueError: Collection SEC-10-K does not exist